CONN SYS AS SYSDBA;

CREATE TABLESPACE MUSICIODAT
   DATAFILE 'C:\oraclexe\app\oracle\oradata\XE\MUSICIODAT.DBF'
   SIZE 100m
   AUTOEXTEND ON
   NEXT 100m
   MAXSIZE 2048m;

CREATE USER musici0usr IDENTIFIED BY musici0pwd default tablespace MUSICIODAT;

GRANT CONNECT, RESOURCE, CREATE VIEW to musici0usr;

