// <auto-generated />
namespace EditoraCrescer.Infraestrutura.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ajusteEmCamposObrigatorios : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ajusteEmCamposObrigatorios));
        
        string IMigrationMetadata.Id
        {
            get { return "201706022253382_ajusteEmCamposObrigatorios"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
